Jp/fix flutter run
akinsho/flutter-tools.nvim pull request #119
Opened 2022-01-14 01:07 UTC by joshpetit

#118 

Fix flutter run not using arguments.

This wont work for emulators, I think I can get it to work by just extending the args again and then using the run method instead of emulator run, but im not sure if that might break something else.

2022-01-14 10:33 UTC, akinsho requested changes
Thanks for this PR 👍🏿 I've made some minor comments to tweak variable names but it looks good in general

2022-01-14 10:33 UTC, akinsho commented on lua/flutter-tools/devices.lua
> +        require("flutter-tools.commands").run({ full_args = args })
same here please 🙏🏿

2022-01-14 10:55 UTC, joshpetit commented on lua/flutter-tools/commands.lua
> +  local full_args = opts.full_args
Yea that's a good choice 👍👍

2022-01-16 01:43 UTC, joshpetit commented
@akinsho just fixed the pipeline, I was using a different formatter before.

2022-01-16 14:21 UTC, akinsho approved these changes
Thanks for the tweaks @joshpetit, this LGTM haven't tested it out myself but should be fine 👍🏿 🤞🏿

2022-01-16 14:22 UTC, merged