feat(lsp): support dart/textDocument/super method
akinsho/flutter-tools.nvim pull request #169
Opened 2022-07-22 18:10 UTC by changyiyao

Add a new command `FlutterSuper` to invoke the dart lsp method to navigate to its `super`.

2022-07-23 09:09 UTC, akinsho requested changes
LGTM generally but the function needs to be added to the right module and imported here instead.

2022-07-23 09:09 UTC, akinsho commented on lua/flutter-tools.lua
> +    lsp.buf_request(
@changyiyao can you move this logic to the lsp module I don't think logic like this should be done inline inside the flutter tools entry point file but rather inside the relevant module then imported here

2022-07-23 09:09 UTC, akinsho commented on ftplugin/dart/lsp.lua
> -if vim.b.did_ftplugin_dart_lsp then
Normally this should be in a separate PR since your changes don't mention this at all but it's fine since it's a small change

2022-07-23 13:46 UTC, changyiyao commented on lua/flutter-tools.lua
> +    lsp.buf_request(
@akinsho Thanks, Let me have a try

2022-07-26 12:11 UTC, akinsho commented
@changyiyao I've rebased your changes and moved the logic into the lsp module on my side but can't push to your branch to update it as I was going to merge it once my changes were pushed. Anyway you don't need the additional changes your branch as I've added fixes in main for those. All you need to do now is just move the logic to `flutter-tools/lsp` and require in the function

```lua
-- In lsp.lua

function M.super()
  lsp.buf_request(
    0,
    "dart/textDocument/super",
    lsp.util.make_position_params(),
    lsp.handlers["textDocument/definition"]
  )
end
```
Then in `flutter-tools.lua`
```lua
  cmd("FlutterSuper", function()
    require("flutter-tools.lsp").super()
  end, {})
```

2022-07-27 05:39 UTC, closed without merging