fix: do not attach LSP to buffer with diffview file URI
akinsho/flutter-tools.nvim pull request #191
Opened 2022-11-09 21:19 UTC by sidlatau

I am using [diffview](https://github.com/sindrets/diffview.nvim) plugin, but when trying to open file history I am getting 4 error messages (see screenshot below). LSP server tries to attach to history files but fails because the path starts with `diffview://`. 

The simplest solution is to ignore these buffers. That is what I did in this PR. But not sure if this is the best solution - there could be other plugins that use other file prefixes, so in that case, we need to update the plugin again. One idea was not to attach LSP if the buffer is not modifiable, but that option is added later than attach event.

(We should also fix the problem, that there are 4 error messages instead of 2 and some of them are without any message)

<img width="961" alt="image" src="https://user-images.githubusercontent.com/4973296/200941916-af81cf51-d9ab-40e6-ab68-b764347a1a1b.png">

2022-11-12 18:34 UTC, sidlatau commented
I updated  PR to work in a more generic way: instead of checking for invalid buffer path prefixes it will check if the path has a URI prefix and if it does - is it a `file://` prefix. If not - LSP will not be attached. 
What is your opinion about this implementation, @akinsho?

2022-11-16 17:19 UTC, akinsho commented
@sidlatau that sounds good to me 👍🏿, always in favour of more generic solutions where possible

2022-11-16 17:22 UTC, akinsho requested changes
Looks good in general, just made one comment about maybe simplifying a conditional

2022-11-16 17:22 UTC, akinsho commented on lua/flutter-tools/lsp/init.lua
> +  if start_index and uri_prefix ~= "file://" then
This could be simplified to 
```lua
return not start_index or uri_prefix == "file://"
```

Rather than return false, then true. The conditional might not be entirely right though, so please check.

2022-11-17 18:49 UTC, akinsho approved these changes
LGTM

2022-11-17 18:49 UTC, merged