feat: add ability to view selected project config in statusline
akinsho/flutter-tools.nvim pull request #241
Opened 2023-04-11 17:48 UTC by sidlatau

Selecting works, but unselecting does not, looks like that `shutdown` function is not called. Also, I see there is `FlutterToolsAppStarted` autocommand, but it does not work for me if I use it. So I created a new one here. 
@akinsho  what is your opinion about adding this info to decorations?

2023-04-12 19:14 UTC, sidlatau commented
Fixed problem with unselecting project config. Here is an object I am using it in lualine:
```lua
    local flutter_project_config = {
      function()
        local decorations = vim.g.flutter_tools_decorations or {}
        local project_config = decorations.project_config or {}
        return project_config.name or ""
      end,
      color = { fg = colors.green, gui = "bold" },
    }


```

2023-04-13 07:30 UTC, akinsho requested changes
@sidlatau I'm open to exposing the config as a statusline variable but I'd rather avoid emitting an autocommand all over the place for this. Maybe look into using a `vim.g.` variable instead I havent thought it through how it might interact with other statusline variables. I sort of just added that module and haven't really iterated

2023-04-13 07:36 UTC, akinsho commented on lua/flutter-tools/commands.lua
> +  api.nvim_exec_autocmds("User", { pattern = "FlutterToolsProjectConfigChanged" })
Actually another thought I had was that you can use the data field of an autocommand to pass the current config is emitting autocommand events so you don't need to store this variable in this file.

You can create an event emit util which just wraps executing an autocommand but send the data as well

2023-04-15 10:46 UTC, sidlatau commented on lua/flutter-tools/commands.lua
> +  api.nvim_exec_autocmds("User", { pattern = "FlutterToolsProjectConfigChanged" })
@akinsho, I updated the code.

2023-04-15 10:53 UTC, akinsho reviewed
I've left a quick comment about refactoring the event emissions I can push a commit to do this and you can pull that in or you can add it in here depending on your preference

2023-04-15 10:53 UTC, akinsho commented on lua/flutter-tools/commands.lua
> +      api.nvim_exec_autocmds(
@sidlatau I'd like to refactor the event emission to use a consistent interface that does stuff like makes sure the names of the events are consistent and standardised like
```lua
utils.emit_event(utils.events.PROJECT_CONFIG_CHANGED, {data: name})

-- in utils.lua

---@enum
M.events = {
	PROJECT_CONFIG_CHANGED = "ProjectConfigChanged",
}

---@generic T:table
---@param events events | events[]
---@param data {data: T}
function M.emit_event(events, opts)
  local e = M.map(function(ev) return prefix .. ev end, events)
  api.nvim_exec_autocommand(events, opts)
end
```

2023-04-15 15:13 UTC, sidlatau commented on lua/flutter-tools/commands.lua
> +      api.nvim_exec_autocmds(
Events emission logic was extracted. I also refactored all places that used `nvim_exec_autocommand`.

2023-04-15 15:39 UTC, akinsho approved these changes
LGTM, thanks for adding in the changes 🙏🏾

2023-04-15 15:41 UTC, merged